name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Frontend install & build
        run: |
          if [ -f package.json ]; then
            corepack enable || true
            if [ -f pnpm-lock.yaml ]; then pnpm i --frozen-lockfile; else npm ci || npm i; fi
            npm run build || echo "skip FE build"
          fi

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_mysql, intl, zip

      - name: PHP deps & tests
        run: |
          if [ -f composer.json ]; then
            composer install --no-interaction --prefer-dist
            if [ -f vendor/bin/phpunit ]; then vendor/bin/phpunit || true; fi
          fi

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        if: github.ref == 'refs/heads/main'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push Docker images (main only)
        if: github.ref == 'refs/heads/main'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO_BACKEND: ${{ secrets.ECR_REPO_BACKEND }}
          ECR_REPO_FRONTEND: ${{ secrets.ECR_REPO_FRONTEND }}
          SHA: ${{ github.sha }}
        run: |
          docker build -f docker/backend/Dockerfile -t $ECR_REGISTRY/$ECR_REPO_BACKEND:$SHA .
          docker build -f docker/frontend/Dockerfile -t $ECR_REGISTRY/$ECR_REPO_FRONTEND:$SHA .
          docker push $ECR_REGISTRY/$ECR_REPO_BACKEND:$SHA
          docker push $ECR_REGISTRY/$ECR_REPO_FRONTEND:$SHA
