version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    ports:
      - "${BACKEND_PORT}:8080"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "${FE_PORT}:5173"
    depends_on:
      - backend

volumes:
  dbdata:
